#CONTENT UPDATE 001
print("where do cows go to vacations? \n to the Mooooooovies")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("AT SQUID GAME, GAME 4: /n guy1: make sure you dont lose your marbles ! /n guy2: i got a better one.... are you an calendar? because you're face is a number!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("doubble jokes at a time!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("what do you call a belt made out of watches? /n a waist of time")
print("teacher: STAND UP /n student: I will stand up... is that all you got? /n teacher: stand up outside of the classroom for the entire class. /n student: I will stand outide of the classroom... is that all you got? /n teacher: while lifting your chair and standing up with one leg. /n student: *gulp*")
