#CONTENT UPDATE 002

print("Why did the tomato blush? \n Because it saw the salad dressing.")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("What’s orange and sounds like a parrot? /n A Carrot")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("What did Mr. and Mrs. Hamburger name their daughter? \n Patty!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Why does Humpty Dumpty love autumn? \n Because he always has a great fall.")

#code
c1 = input("code: ")
if c1 == "y3s":
  print("yup you got it right follow me on twitter for more codes! link: https://twitter.com/CoderRudra?t=niKr3fHP2a8D9jQuwrenLg&s=09")
else:
  print(">:( FOLLOW RUDRA ON TWITTER LINK: https://twitter.com/CoderRudra?t=niKr3fHP2a8D9jQuwrenLg&s=09")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("What do you call a group of berries playing instruments? \n A jam session.")
